### ISSUE TITLE
Config-Popup crashes if "localname" is not set

### ISSUE THREAD

**Issue by Jakob-Gliwa** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#108]
When trying to open a Config-Popup for an element that has an undefined type (see pic), popup show up but quickly closes.
![image](https://user-images.githubusercontent.com/6706297/137647782-6850d348-8ddb-457d-83c3-efaf8a12e9cd.png)

Console Output:
![image](https://user-images.githubusercontent.com/6706297/137647826-53087e17-e15a-4324-842c-3ba4cd94cbf6.png)

I suggest fixing 2 things:
1) Make settings more robust against undefined type-fields
2) Check wether all entries should have a type and fix the missing ones

**Comment by christianTF** [comment]
This is already fixed in the main branch.
https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/commit/db19179ff9fa158a4a6fdb253de764421b853009
