### ISSUE TITLE
"Default" attribute difficult to map for MQTTLive 

### ISSUE THREAD

**Issue by Jakob-Gliwa** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#111]
Example topic: **"publish s4l/mqttlive/1/Intelligente_Raumregelung_Badezimmer/Default <v.3>"**

When using MQTTLive it is needed to connect the Loxone component with the virtual output command that sends the data via MQTT. 

I'm not too deep into the topic, but I see two potential problems with the "Default" values in this context:
1. Finding the right output for "Default" attributes seems to be non-trivial (for example for the "Intelligente Raumregelung"). 
2.  As far as I understand "Default" and "AQ" (for example for sensors) can give different values. But when using MQTTLive one would have to connect the "Default" output to AQ on the sensor, right? Wouldn't that result in a Jitter in the resulting data set?

Problem 1 could be fixed by either hinting to the right Attribute in the MQTTLive-Config-GUI or by adapting the topic naming pattern (e.g. to s4l/mqttlive/1/Intelligente_Raumregelung_Badezimmer/HC/Default).

I don't really have a good suggestion for problem 2 (if it really is one) besides removing "Default" attributes from MQTTLive or prompting an information to the user about this caveat.

Thank you for your great work on this plugin!!!

**Comment by christianTF** [comment]
Closed because of inactivity
