### ISSUE TITLE
MQTT Collector hat ein Problem mit "/" am Beginn der Subscription

### ISSUE THREAD

**Issue by RiverRaid** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#119]
Hy an alle!

Bei mir ist folgendes Problem: Mein go-eCharger stellt der Subscription ein "/" voran, weshalb auch immer..., dh als Subscription muss "/go-eCharger/066735/eto" eingetragen werden (anstatt "go-eCharger/066735/eto" wie bei allen Anderen)

Nur dann ist es auch in der QUERY-FROM auffindbar. Allerdings findet er dann nichts unter SELECT => field(value)

LG

**Comment by RiverRaid** [comment]
Hier noch die passenden Screenshots:

![go-e1](https://user-images.githubusercontent.com/4259790/144609191-272d9a0a-70cb-4e67-8c31-fc65ef58853a.png)
![go-e2](https://user-images.githubusercontent.com/4259790/144609197-7951d28b-117a-48f8-aa0a-6ebb60683722.png)
![go-e3](https://user-images.githubusercontent.com/4259790/144609201-b22de1fb-ddee-49b8-8d2e-e5570e42684d.png)

**Comment by christianTF** [comment]
Das scheint ein Problem von Grafana zu sein.

![image](https://user-images.githubusercontent.com/14220265/144716419-84852ccb-7ec1-4cad-996a-a7b9d8cc0991.png)

In der Influx-Datenbank ist das Field mit dem richtigen Key enthalten.

@RiverRaid Mein Vorschlag wäre:
Bei Einzelwerten nehme ich als measurement ein Level darüber, und als Field das letzte Level.

Zum Beispiel:
Dein eingehender Datensatz `/go-eCharger/066735/eto` würde zu 
measurement: `/go-eCharger/066735`
field: `eto`

Kommt ein anderer Datensatz `/go-eCharger/066735/uta` würde das im gleichen Measurement mit anderen Field landen:
measurement: `/go-eCharger/066735`
field: `uta`

Für den Fall, dass es kein übergeordnetes Topic gibt, würde measurement und field gleich sein, z.B. bei einem Topic `incoming` oder Topic `/incoming`
measurement: `incoming'
field: `incoming`

Bereits bestehende Stats müsstest du in Grafana anpassen.

Was hältst du davon?

**Comment by RiverRaid** [comment]
Servus,Danke für Deine Mühen!!!Dein Vorschlag klingt gut und auch ziemlich logisch :) Dass Measurement und Field bei den Shellies zB auch gleich war, hat mich eh gewundert, dachte aber, dass muss so sein (kenne mich bei influx und grafana leider viel zu wenig aus) ;)Wenn Du etwas benötigst (testen, Fernzugriff oä), bitte gib Bescheid :)LgAm 04.12.2021 17:33 schrieb Christian Fenzl ***@***.***>:

Das scheint ein Problem von Grafana zu sein.



In der Influx-Datenbank ist das Field mit dem richtigen Key enthalten.

@RiverRaid Mein Vorschlag wäre:

Bei Einzelwerten nehme ich als measurement ein Level darüber, und als Field das letzte Level.

Zum Beispiel:

Dein eingehender Datensatz /go-eCharger/066735/eto würde zu

measurement: /go-eCharger/066735

field: eto

Kommt ein anderer Datensatz /go-eCharger/066735/uta würde das im gleichen Measurement mit anderen Field landen:

measurement: /go-eCharger/066735

field: uta

Für den Fall, dass es kein übergeordnetes Topic gibt, würde measurement und field gleich sein, z.B. bei einem Topic incoming oder Topic /incoming

measurement: incoming' field: incoming`

Bereits bestehende Stats müsstest du in Grafana anpassen.

Was hältst du davon?
