### ISSUE TITLE
FR: Use external servers

### ISSUE THREAD

**Issue by mr-manuel** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#122]
Hello,

first of all, thank you very much for this great plugin.

I would like to use an external Influx database, Grafana dashboard and MQTT server, since I'm running them on a server in Docker. Would it be possible to add a setting page, where you can enable/disable the local services (InfluxDB, Grafana) and to specify the IP and port of the external server?

In the meanwhile is it possible to do this manually? Can you tell me which files I have to edit?

**Comment by christianTF** [comment]
Things are on the roadmap but with currently no schedule.

To collect data, you primarily have to edit your Telegraf Config:
https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/tree/main/config/telegraf

but Influx and Grafana needs to be configured by your own.

Grafana plots on the S4L will fail, and automatic provisioning in Grafana is not possible on remote servers, but you will manage to create your dashboards yourself.

No further support possible, also it’s everytime possible that an S4L update kills your custom settings.

Good luck!

**Comment by mr-manuel** [comment]
Thanks for the fast answer. Important was to know, if it was enough to change the telegraf configuration to use InfluxDB for all imports/writes of the Loxone Statistics.

It works :) all other is no problem.

Have a nice weekend

**Comment by christianTF** [comment]
To completeness:
For MQTT configure your foreign broker in MQTT Gateway.
