### ISSUE TITLE
Update auf Grafana Version 9 - Änderung Auth

### ISSUE THREAD

**Issue by flibbi2** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#127]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/315626-stats4lox-das-statistik-plugin?p=353027#post353027

Authentifizierung ändert sich beim Update auf Grafana Version 9.

**Comment by mschlenstedt** [comment]
https://www.loxforum.com/forum/projektforen/loxberry/plugins/315626-stats4lox-das-statistik-plugin?p=350217#post350217

**Comment by mschlenstedt** [comment]
Re Open - has to be checked if this works in a fresh installation.

Also maybe we should explicetley stick to Grafana 9 now as we did fpr the InfluxDB?
