### ISSUE TITLE
Submenu missing in LB3.0

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#130]
![image](https://user-images.githubusercontent.com/14220265/210328239-60b6b8f6-d3d9-40cd-ae92-571cbb169753.png)

Die Untermenüs der Navbar fehlen komplett.

LB3.0 kann nativ Untermenüs, dann gingen diese aber in LB2.2 nicht mehr. 
Oder reparieren und nicht die LB3.0 Navbar verwenden.

**Comment by mschlenstedt** [comment]
MinVersion 3.0 und gut ist.
