### ISSUE TITLE
Extract language specific block names

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#2]
Ich habe im LoxPlan die Types der Bausteine, Zb. Type="Add" (Addierer), Type="VirtualIn" (Virtueller Eingang), und bräuchte irgendwoher die sprachspezifischen Namen.
Am besten zumindest Deutsch und Englisch. 

Evt kann man das irgendwo aus der Loxone Config (Sprachfiles) extrahieren.

**Comment by mschlenstedt** [comment]
Ich kann es erst heute Abend zu Hause testen, aber das Translation Toolkit scheint die QM-Dateien lesen zu können:

http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/qm.html
https://github.com/translate/translate/releases

Die Dateien liegen unter C:\Program Files (x86)\Loxone\LoxoneConfig\translations

**Comment by christianTF** [comment]
https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/commit/94db826a7b5baa79f5fce0741af184a49bcbed16
