### ISSUE TITLE
Uninstall: Aufräumen von /dev/shm/s4ltmp

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#26]
Nach der *Neu*-Installation von S4L hab ich gleich ein paar fertige Imports ;-)

![image](https://user-images.githubusercontent.com/14220265/116032991-df65e400-a660-11eb-940e-b712fbdc76bb.png)

- [ ] pkill von `import_scheduler.pl`
- [ ] pkill von `import_loxone.pl`
- [ ] pkill von `mqttlive.php`
- [ ] Cleanup von `$Globals::s4ltmp`

**Comment by mschlenstedt** [comment]
Fixed in efd2c3ec13d1cc3fcd764a34d1527371cb05701c
