### ISSUE TITLE
Missing Perl Lib for inet_aton

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#36]
`ERROR: loxplan2json: Error running procedure: Undefined subroutine &Loxone::ParseXML::inet_aton called at /opt/loxberry/webfrontend/htmlauth/plugins/stats4lox-ng/../../../../bin/plugins/stats4lox-ng/libs/Loxone/ParseXML.pm line 139.`

**Comment by christianTF** [comment]
Kannst du das mit dem Fix nochmal probieren?

Es wird hier ein DNS-Lookup ausgeführt, wenn im LoxPlan bei der internen Adresse ein Hostname statt einer IP steht (ich brauche die IP, damit ich den Match zur LoxBerry Miniserver-Tabelle machen kann).

Bei dem DNS-Lookup-Code hat die Qualifizierung der Library `Socket` beim Funktionsaufruf gefehlt.
