### ISSUE TITLE
Possibility to enable/disable mqttlive

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#39]
Should be placed in ajax.cgi:

If mqttlive is stopped, it should be disabled and not be started again after reboot. If enabled, it should start on boot.

Should be configrable in stats4lox.json (and Globals.pl).

**Comment by christianTF** [comment]
- [ ] stats4lox.json: enabled/disabled setting (default: enabled)
- [ ] Install: Parse setting
- [ ] Cron.reboot: Parse setting
- [ ] MQTT Live UI: Parse setting and disable UI
