### ISSUE TITLE
Grabber liefert die "source" nicht mit

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#50]
Beim Filtern auf das Tag `source` habe ich die grabber-Datenpunkte nicht zur Auswahl

![image](https://user-images.githubusercontent.com/14220265/117780603-141c9280-b240-11eb-84b3-729af3db877b.png)

Der Grabber sollte auch das source-Tag setzen.

**Comment by mschlenstedt** [comment]
Grabber muss auf lox2telegraf umbauen https://www.loxwiki.eu/display/LOXBERRY/Stats4Lox%3A%3Alox2telegraf
