### ISSUE TITLE
Hostname matching LoxPlan<->LoxBerry not working with hostnames

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#52]
Bei mir ist ne Menge "null".
![image](https://user-images.githubusercontent.com/20454116/117826806-beaca980-b270-11eb-9492-3671ad93f1a1.png)

Loxone Config - Interne Adresse: miniserver.woersty.com

![image](https://user-images.githubusercontent.com/20454116/117826978-e13ec280-b270-11eb-9bc5-1d660f0e0d38.png)

**Comment by christianTF** [comment]
```
WARNING: Found Miniserver Miniserver possibly configured with hostname. Querying IP of miniserver.w*****.com ...
 WARNING: --> Found Miniserver Miniserver and DNS lookup got IP 192.168.178.253 ...
 OK: Parameters ok - responding with HTTP 200
```

**Comment by christianTF** [comment]
Should be fixed with https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/commit/fc4f7222021ceb3278b5393fde227229b07c7111

@Woersty Closed du, wenn's gefixt ist?

**Comment by Woersty** [comment]
![image](https://user-images.githubusercontent.com/20454116/117857755-6afc8900-b28d-11eb-8a20-a10660b02a14.png)

**Comment by christianTF** [comment]
Fixed with https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/commit/445b8f7653208711c737366daa40533af4e4c379
