### ISSUE TITLE
Import exception if Loxone Statistic Timestamp is during invalid time offset area

### ISSUE THREAD

**Issue by flibbi2** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#53]
21:07:56.033 INFO: LoxBerry Version 2.2.0.5 ( is_vmware.cfg is_x64.cfg )
21:07:56.033 INFO: Stats4Lox Version 0.0.1
21:07:56.033 INFO: Loglevel: 7
21:07:56.041 Loxone::Import::statusgetfile--> Creating status file
21:07:56.045 INFO: Loxone::Import::statusgetfile--> Status file: /opt/loxberry/data/plugins/stats4lox/import/import_3_16e9eac3-03a5-7dd1-ffff9a8dad1579a8.json
21:07:56.045 INFO: --> Logfile: /opt/loxberry/log/plugins/stats4lox/20210511_210756_012_Import_Stats.log
21:07:56.045 Loxone::Import::new--> Called
21:07:56.045 Loxone::Import::getStatsjsonElement--> Called
21:07:56.045 Loxone::Import::getStatsjsonElement--> Opening stats.json (/opt/loxberry/config/plugins/stats4lox/stats.json)
21:07:56.046 Loxone::Import::getStatsjsonElement--> Searching for 16e9eac3-03a5-7dd1-ffff9a8dad1579a8 and 3
21:07:56.046 Loxone::Import::getStatsjsonElement--> Found 1 elements
21:07:56.046 Loxone::Import::getStatsjsonElement--> Found stat name Energiemonitor
21:07:56.046 INFO: Loxone::Import::getLoxoneLabels--> Querying MS3 to get output labels
mshttp_call2: timeout=5
mshttp_call2: HTTP 200: 200 OK

mshttp_call2:Some lines of the response:
{&quot;LL&quot;: { &quot;control&quot;: &quot;dev/sps/io/16e9eac3-03a5-7dd1-ffff9a8dad1579a8/all&quot;, &quot;value&quot;: &quot;0.000&quot;, &quot;Code&quot;: &quot;200&quot;,
&quot;output0&quot;: { &quot;name&quot;: &quot;AQp&quot;, &quot;nr&quot;: 1, &quot;value&quot;: 0.000},
&quot;output1&quot;: { &quot;name&quot;: &quot;AQp1&quot;, &quot;nr&quot;: 2, &quot;value&quot;: 21.197},
&quot;output2&quot;: { &quot;name&quot;: &quot;AQp2&quot;, &quot;nr&quot;: 3, &quot;value&quot;: 567.082},
&quot;output3&quot;: { &quot;name&quot;: &quot;AQp3&quot;, &quot;nr&quot;: 4, &quot;value&quot;: 3275.337},
&quot;output4&quot;: { &quot;name&quot;: &quot;AQp4&quot;, &quot;nr&quot;: 5, &quot;value&quot;: 3275.337},
&quot;output5&quot;: { &quot;name&quot;: &quot;AQc&quot;, &quot;nr&quot;: 6, &quot;value&quot;: 1.375},
&quot;output6&quot;: { &quot;name&quot;: [...]
21:07:56.137 Loxone::Import::setMappings--> Called
21:07:56.137 Loxone::Import::setMappings--> Stat element type is Fronius
21:07:56.138 INFO: Loxone::Import::setMappings--> Used mapping is: «0»→«Default»
21:07:56.138 Loxone::Import::getStatlist--> Called
21:07:56.138 Loxone::Import::getStatlist--> Checking for cached statlist of 3
21:07:56.138 Loxone::Import::getStatlist--> Acquiring download lock for Miniserver 3
21:07:56.138 Loxone::Import::getStatlist--> Requesting stat list from Miniserver 3 (Try 1/3)
mshttp_call2: timeout=120
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;html&gt;&lt;head&gt;
&lt;title&gt;Statistics&lt;/title&gt;
&lt;link href=&quot;styles.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;screen&quot; /&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;Statistics&lt;/h1&gt;
&lt;ul&gt;
&lt;li&gt;&lt;a href=&quot;17398922-0051-128c-ffff9a8dad1579a8.202105.xml&quot;&gt;Betriebszeitz&amp;#xE4;hler (Hausger&amp;#xE4;te Diele) 202105&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml&quot;&gt;Energiemonitor (Photovoltaik Zentral) 202103&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202104.xml&quot;&gt;Energiemonitor (Photovoltaik Zentra [...]
21:07:56.327 Loxone::Import::getStatlist--> Saving response to cachefile /dev/shm/s4ltmp/msstatlist_ms3.tmp
21:07:56.327 Loxone::Import::getStatlist--> Parsing response
21:07:56.327 Loxone::Import::getStatlist--> Number of lines 23
21:07:56.327 Loxone::Import::getStatlist--> Number of different uuids 6
21:07:56.327 Loxone::Import::getStatlist--> Finished ok
21:07:56.327 --> Statlist 2 elements.
21:07:56.327 INFO: --> Fetching 16e9eac3-03a5-7dd1-ffff9a8dad1579a8 Month: 202103
21:07:56.327 Loxone::Import::getMonthStat--> Called
21:07:56.328 Loxone::Import::getMonthStat--> Acquiring download lock for Miniserver 3
21:07:56.328 Loxone::Import::getMonthStat--> Querying stat for month 202103 (Try 1/5)
21:07:56.328 Loxone::Import::getMonthStat--> url: /stats/16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml
mshttp_call2: timeout=120
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;Statistics Name=&quot;Energiemonitor&quot; NumOutputs=&quot;9&quot; Outputs=&quot;Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug&quot;&gt;
&lt;S T=&quot;2021-03-08 10:56:14&quot; V=&quot;0.000&quot; V2=&quot;0.000&quot; V3=&quot;0.000&quot; V4=&quot;0.000&quot; V5=&quot;0.000&quot; V6=&quot;0.000&quot; V7=&quot;0.000&quot; V8=&quot;0.000&quot; V9=&quot;0.000&quot;/&gt;
&lt;S T=&quot;2021-03-08 10:57:05&quot; V=&quot;1.877&quot; V2=&quot;3.157&quot; V3=&quot;1.332&quot; V4=&quot;-0.051&quot; V5=&quot;13.500&quot; V6=&quot;0.421&quot; V7=&quot;0.000&quot; [...]
21:07:57.710 OK: Loxone::Import::getMonthStat--> HTTP 200 OK
21:07:57.710 Loxone::Import::parseStatXML_REGEX--> Reading XML (REGEX)
21:07:57.715 Loxone::Import::parseStatXML_REGEX--> Name:Energiemonitor Outputs:(Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug) NumOutputs:9
21:07:58.089 Loxone::Import::parseStatXML_REGEX--> Readed 2000 records
21:07:58.486 Loxone::Import::parseStatXML_REGEX--> Readed 4000 records
21:07:58.493 WARNING: Loxone::Import::getMonthStat--> Download possibly corrupt --> Invalid local time for date in time zone: Europe/Berlin

21:07:58.494 WARNING: Loxone::Import::getMonthStat--> Sleeping 5 seconds before retry...
21:08:03.494 Loxone::Import::getMonthStat--> Acquiring download lock for Miniserver 3
21:08:03.494 Loxone::Import::getMonthStat--> Querying stat for month 202103 (Try 2/5)
21:08:03.494 Loxone::Import::getMonthStat--> url: /stats/16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml
mshttp_call2: timeout=240
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;Statistics Name=&quot;Energiemonitor&quot; NumOutputs=&quot;9&quot; Outputs=&quot;Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug&quot;&gt;
&lt;S T=&quot;2021-03-08 10:56:14&quot; V=&quot;0.000&quot; V2=&quot;0.000&quot; V3=&quot;0.000&quot; V4=&quot;0.000&quot; V5=&quot;0.000&quot; V6=&quot;0.000&quot; V7=&quot;0.000&quot; V8=&quot;0.000&quot; V9=&quot;0.000&quot;/&gt;
&lt;S T=&quot;2021-03-08 10:57:05&quot; V=&quot;1.877&quot; V2=&quot;3.157&quot; V3=&quot;1.332&quot; V4=&quot;-0.051&quot; V5=&quot;13.500&quot; V6=&quot;0.421&quot; V7=&quot;0.000&quot; [...]
21:08:04.983 OK: Loxone::Import::getMonthStat--> HTTP 200 OK
21:08:04.983 Loxone::Import::parseStatXML_REGEX--> Reading XML (REGEX)
21:08:04.987 Loxone::Import::parseStatXML_REGEX--> Name:Energiemonitor Outputs:(Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug) NumOutputs:9
21:08:05.338 Loxone::Import::parseStatXML_REGEX--> Readed 2000 records
21:08:05.701 Loxone::Import::parseStatXML_REGEX--> Readed 4000 records
21:08:05.708 WARNING: Loxone::Import::getMonthStat--> Download possibly corrupt --> Invalid local time for date in time zone: Europe/Berlin

21:08:05.709 WARNING: Loxone::Import::getMonthStat--> Sleeping 20 seconds before retry...
21:08:25.709 Loxone::Import::getMonthStat--> Acquiring download lock for Miniserver 3
21:08:25.709 Loxone::Import::getMonthStat--> Querying stat for month 202103 (Try 3/5)
21:08:25.709 Loxone::Import::getMonthStat--> url: /stats/16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml
mshttp_call2: timeout=360
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;Statistics Name=&quot;Energiemonitor&quot; NumOutputs=&quot;9&quot; Outputs=&quot;Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug&quot;&gt;
&lt;S T=&quot;2021-03-08 10:56:14&quot; V=&quot;0.000&quot; V2=&quot;0.000&quot; V3=&quot;0.000&quot; V4=&quot;0.000&quot; V5=&quot;0.000&quot; V6=&quot;0.000&quot; V7=&quot;0.000&quot; V8=&quot;0.000&quot; V9=&quot;0.000&quot;/&gt;
&lt;S T=&quot;2021-03-08 10:57:05&quot; V=&quot;1.877&quot; V2=&quot;3.157&quot; V3=&quot;1.332&quot; V4=&quot;-0.051&quot; V5=&quot;13.500&quot; V6=&quot;0.421&quot; V7=&quot;0.000&quot; [...]
21:08:27.080 OK: Loxone::Import::getMonthStat--> HTTP 200 OK
21:08:27.080 Loxone::Import::parseStatXML_REGEX--> Reading XML (REGEX)
21:08:27.085 Loxone::Import::parseStatXML_REGEX--> Name:Energiemonitor Outputs:(Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug) NumOutputs:9
21:08:27.494 Loxone::Import::parseStatXML_REGEX--> Readed 2000 records
21:08:27.917 Loxone::Import::parseStatXML_REGEX--> Readed 4000 records
21:08:27.925 WARNING: Loxone::Import::getMonthStat--> Download possibly corrupt --> Invalid local time for date in time zone: Europe/Berlin

21:08:27.926 WARNING: Loxone::Import::getMonthStat--> Sleeping 45 seconds before retry...
21:09:12.926 Loxone::Import::getMonthStat--> Acquiring download lock for Miniserver 3
21:09:12.926 Loxone::Import::getMonthStat--> Querying stat for month 202103 (Try 4/5)
21:09:12.926 Loxone::Import::getMonthStat--> url: /stats/16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml
mshttp_call2: timeout=480
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;Statistics Name=&quot;Energiemonitor&quot; NumOutputs=&quot;9&quot; Outputs=&quot;Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug&quot;&gt;
&lt;S T=&quot;2021-03-08 10:56:14&quot; V=&quot;0.000&quot; V2=&quot;0.000&quot; V3=&quot;0.000&quot; V4=&quot;0.000&quot; V5=&quot;0.000&quot; V6=&quot;0.000&quot; V7=&quot;0.000&quot; V8=&quot;0.000&quot; V9=&quot;0.000&quot;/&gt;
&lt;S T=&quot;2021-03-08 10:57:05&quot; V=&quot;1.877&quot; V2=&quot;3.157&quot; V3=&quot;1.332&quot; V4=&quot;-0.051&quot; V5=&quot;13.500&quot; V6=&quot;0.421&quot; V7=&quot;0.000&quot; [...]
21:09:14.361 OK: Loxone::Import::getMonthStat--> HTTP 200 OK
21:09:14.361 Loxone::Import::parseStatXML_REGEX--> Reading XML (REGEX)
21:09:14.365 Loxone::Import::parseStatXML_REGEX--> Name:Energiemonitor Outputs:(Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug) NumOutputs:9
21:09:14.874 Loxone::Import::parseStatXML_REGEX--> Readed 2000 records
21:09:15.449 Loxone::Import::parseStatXML_REGEX--> Readed 4000 records
21:09:15.461 WARNING: Loxone::Import::getMonthStat--> Download possibly corrupt --> Invalid local time for date in time zone: Europe/Berlin

21:09:15.462 WARNING: Loxone::Import::getMonthStat--> Sleeping 80 seconds before retry...
21:10:35.463 Loxone::Import::getMonthStat--> Acquiring download lock for Miniserver 3
21:10:35.463 Loxone::Import::getMonthStat--> Querying stat for month 202103 (Try 5/5)
21:10:35.463 Loxone::Import::getMonthStat--> url: /stats/16e9eac3-03a5-7dd1-ffff9a8dad1579a8.202103.xml
mshttp_call2: timeout=600
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;Statistics Name=&quot;Energiemonitor&quot; NumOutputs=&quot;9&quot; Outputs=&quot;Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug&quot;&gt;
&lt;S T=&quot;2021-03-08 10:56:14&quot; V=&quot;0.000&quot; V2=&quot;0.000&quot; V3=&quot;0.000&quot; V4=&quot;0.000&quot; V5=&quot;0.000&quot; V6=&quot;0.000&quot; V7=&quot;0.000&quot; V8=&quot;0.000&quot; V9=&quot;0.000&quot;/&gt;
&lt;S T=&quot;2021-03-08 10:57:05&quot; V=&quot;1.877&quot; V2=&quot;3.157&quot; V3=&quot;1.332&quot; V4=&quot;-0.051&quot; V5=&quot;13.500&quot; V6=&quot;0.421&quot; V7=&quot;0.000&quot; [...]
21:10:36.689 OK: Loxone::Import::getMonthStat--> HTTP 200 OK
21:10:36.690 Loxone::Import::parseStatXML_REGEX--> Reading XML (REGEX)
21:10:36.695 Loxone::Import::parseStatXML_REGEX--> Name:Energiemonitor Outputs:(Leistung Produktion,Leistung Verbrauch,Leistung Energieversorger,Leistung Batterie,Ladestand Batterie,Z�hler Produktion,Z�hler Verbrauch,Z�hler Lieferung,Z�hler Bezug) NumOutputs:9
21:10:37.107 Loxone::Import::parseStatXML_REGEX--> Readed 2000 records
21:10:37.546 Loxone::Import::parseStatXML_REGEX--> Readed 4000 records
21:10:37.559 CRITICAL: --> getMonthStat 202103: Invalid local time for date in time zone: Europe/Berlin

21:10:37.561 Loxone::Import::DESTROY-->: Called
21:10:37.562 CRITICAL: main::END--> Import exited with error.
 11.05.2021 21:10:37 TASK FINISHED

[energymonitor.txt](https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/files/6461634/energymonitor.txt)

**Comment by christianTF** [comment]
![image](https://user-images.githubusercontent.com/14220265/117961877-e8240e80-b31e-11eb-82fb-220ff7e569f8.png)

Das betrifft nicht nur den Energymonitor Baustein, sondern jeden Import.

**Comment by christianTF** [comment]
Neues Verhalten:
- Wenn ein Loxone timestamp eine Exception wirft, wird versucht, **eine Minute** abzuziehen und den Timestamp erneut nach epoch zu konvertieren.
- Ist der Timestamp dann gültig, kommt eine Warning ins Log und der Import setzt fort.
- Ist der Timestamp nach der Modifikation wieder nicht gültig, kommt wieder eine Exception.

Eine Minute statt einer Sekunde deswegen, weil unklar ist, welches Offset maximal in der Loxone Stat vorkommen könnte. Würde Loxone 02:00:01 schreiben, würde es wieder nicht funktionieren. Eine Minute Abzug ist auf der sicheren Seite. Der konkrete Datenpunkt liegt dann eine Minute vor dem eigentlichen Ereignis.

Wenn eine Modifikation um eine Minute nicht reicht, oder das File grundsätzlich invalide ist, bleibt es weiterhin bei einer Exception.
