### ISSUE TITLE
Import Error - No file

### ISSUE THREAD

**Issue by madito** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#54]
22:42:17.947 INFO: LoxBerry Version 2.2.0.5 ( is_vmware.cfg is_x64.cfg )
22:42:17.947 INFO: Stats4Lox Version 0.0.1
22:42:17.948 INFO: Loglevel: 7
22:42:17.970 Loxone::Import::statusgetfile--> Creating status file
22:42:17.980 INFO: Loxone::Import::statusgetfile--> Status file: /opt/loxberry/data/plugins/stats4lox/import/import_1_1691ef8a-01fa-b4c9-ffffd4fcec132aee.json
22:42:17.980 INFO: --> Logfile: /opt/loxberry/log/plugins/stats4lox/20210511_224217_893_Import_Stats.log
22:42:17.982 Loxone::Import::new--> Called
22:42:17.982 Loxone::Import::getStatsjsonElement--> Called
22:42:17.983 Loxone::Import::getStatsjsonElement--> Opening stats.json (/opt/loxberry/config/plugins/stats4lox/stats.json)
22:42:17.983 Loxone::Import::getStatsjsonElement--> Searching for 1691ef8a-01fa-b4c9-ffffd4fcec132aee and 1
22:42:17.984 Loxone::Import::getStatsjsonElement--> Found 1 elements
22:42:17.984 Loxone::Import::getStatsjsonElement--> Found stat name Consumo Total Vivienda
22:42:17.985 INFO: Loxone::Import::getLoxoneLabels--> Querying MS1 to get output labels
mshttp_call2: timeout=5
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
{&quot;LL&quot;: { &quot;control&quot;: &quot;dev/sps/io/1691ef8a-01fa-b4c9-ffffd4fcec132aee/all&quot;, &quot;value&quot;: &quot;809.7&quot;, &quot;Code&quot;: &quot;200&quot;}}
[...]
22:42:18.284 Loxone::Import::setMappings--> Called
22:42:18.284 Loxone::Import::setMappings--> Stat element type is Memory
22:42:18.284 INFO: Loxone::Import::setMappings--> Used mapping is: «0»→«Default»
22:42:18.286 Loxone::Import::getStatlist--> Called
22:42:18.286 Loxone::Import::getStatlist--> Checking for cached statlist of 1
22:42:18.286 Loxone::Import::getStatlist--> Reading cache file /dev/shm/s4ltmp/msstatlist_ms1.tmp
22:42:18.286 Loxone::Import::getStatlist--> Parsing response
22:42:18.287 Loxone::Import::getStatlist--> Number of lines 8
22:42:18.287 Loxone::Import::getStatlist--> Number of different uuids 4
22:42:18.287 Loxone::Import::getStatlist--> Finished ok
22:42:18.287 --> Statlist 0 elements.
22:42:18.287 CRITICAL: --> getStatList: Could not get Statistics list from Loxone Miniserver MS1 --> 
22:42:18.289 Loxone::Import::DESTROY-->: Called
22:42:18.289 CRITICAL: main::END--> Import exited with error.
 11.05.2021 22:42:18 TASK FINISHED
![1](https://user-images.githubusercontent.com/5938785/117882465-aa859e00-b2aa-11eb-9d57-bf9fae278b30.JPG)

**Comment by madito** [comment]
Is available:

```
<Statistics Name="Consumo Total Vivienda" NumOutputs="1" Outputs=";0;0;%.1f">
<S T="2021-05-11 21:36:20" V="682.000"/>
<S T="2021-05-11 21:37:03" V="721.190"/>
<S T="2021-05-11 21:38:07" V="721.470"/>
<S T="2021-05-11 21:39:00" V="721.910"/>
<S T="2021-05-11 21:40:05" V="708.310"/>
<S T="2021-05-11 21:41:09" V="717.330"/>
<S T="2021-05-11 21:42:03" V="705.720"/>
<S T="2021-05-11 21:43:07" V="556.950"/>
<S T="2021-05-11 21:44:01" V="548.010"/>
<S T="2021-05-11 21:45:04" V="547.630"/>
<S T="2021-05-11 21:46:09" V="537.080"/>
<S T="2021-05-11 21:47:02" V="659.660"/>
<S T="2021-05-11 21:48:06" V="621.640"/>
<S T="2021-05-11 21:49:00" V="605.500"/>
<S T="2021-05-11 21:50:04" V="599.990"/>
<S T="2021-05-11 21:51:08" V="649.300"/>
<S T="2021-05-11 21:52:02" V="600.880"/>
<S T="2021-05-11 21:53:06" V="597.530"/>
<S T="2021-05-11 21:54:00" V="597.610"/>
<S T="2021-05-11 21:55:04" V="606.280"/>
<S T="2021-05-11 21:56:08" V="597.450"/>
<S T="2021-05-11 21:57:02" V="604.790"/>
<S T="2021-05-11 21:58:06" V="602.560"/>
<S T="2021-05-11 21:59:00" V="603.940"/>
<S T="2021-05-11 22:00:04" V="651.650"/>
<S T="2021-05-11 22:01:08" V="662.840"/>
<S T="2021-05-11 22:02:01" V="652.830"/>
<S T="2021-05-11 22:03:06" V="604.660"/>
<S T="2021-05-11 22:04:10" V="628.020"/>
<S T="2021-05-11 22:05:03" V="1650.720"/>
<S T="2021-05-11 22:06:08" V="1697.370"/>
<S T="2021-05-11 22:07:01" V="1711.960"/>
<S T="2021-05-11 22:08:06" V="1731.660"/>
<S T="2021-05-11 22:09:10" V="1831.570"/>
<S T="2021-05-11 22:10:03" V="1677.340"/>
<S T="2021-05-11 22:11:07" V="1657.460"/>
<S T="2021-05-11 22:12:01" V="1399.020"/>
<S T="2021-05-11 22:13:05" V="1417.670"/>
<S T="2021-05-11 22:14:10" V="1388.690"/>
<S T="2021-05-11 22:15:03" V="1286.490"/>
<S T="2021-05-11 22:16:09" V="1334.000"/>
<S T="2021-05-11 22:17:03" V="1312.950"/>
<S T="2021-05-11 22:18:08" V="1363.580"/>
<S T="2021-05-11 22:19:01" V="1374.540"/>
<S T="2021-05-11 22:20:06" V="855.200"/>
<S T="2021-05-11 22:21:10" V="2197.560"/>
<S T="2021-05-11 22:22:04" V="2177.540"/>
<S T="2021-05-11 22:23:08" V="2164.440"/>
<S T="2021-05-11 22:24:01" V="2133.140"/>
<S T="2021-05-11 22:25:06" V="930.330"/>
<S T="2021-05-11 22:26:10" V="851.600"/>
<S T="2021-05-11 22:27:03" V="2125.110"/>
<S T="2021-05-11 22:28:08" V="2014.240"/>
<S T="2021-05-11 22:29:01" V="777.630"/>
<S T="2021-05-11 22:30:05" V="2059.560"/>
<S T="2021-05-11 22:31:09" V="790.540"/>
<S T="2021-05-11 22:32:03" V="777.250"/>
<S T="2021-05-11 22:33:07" V="780.690"/>
<S T="2021-05-11 22:34:01" V="778.160"/>
<S T="2021-05-11 22:35:05" V="758.630"/>
<S T="2021-05-11 22:36:09" V="813.890"/>
<S T="2021-05-11 22:37:03" V="811.220"/>
<S T="2021-05-11 22:38:07" V="811.160"/>
<S T="2021-05-11 22:39:01" V="851.130"/>
<S T="2021-05-11 22:40:05" V="853.820"/>
<S T="2021-05-11 22:41:09" V="852.870"/>
<S T="2021-05-11 22:42:03" V="828.490"/>
<S T="2021-05-11 22:43:07" V="802.310"/>
<S T="2021-05-11 22:44:01" V="810.500"/>
<S T="2021-05-11 22:45:05" V="801.540"/>
<S T="2021-05-11 22:46:09" V="813.980"/>
<S T="2021-05-11 22:47:03" V="788.510"/>
<S T="2021-05-11 22:48:07" V="799.470"/>
<S T="2021-05-11 22:49:01" V="772.770"/>
<S T="2021-05-11 22:50:05" V="752.650"/>
<S T="2021-05-11 22:51:08" V="755.550"/>
<S T="2021-05-11 22:52:00" V="777.340"/>
<S T="2021-05-11 22:53:04" V="779.930"/>
<S T="2021-05-11 22:54:08" V="866.810"/>
<S T="2021-05-11 22:55:02" V="851.460"/>
<S T="2021-05-11 22:56:06" V="846.850"/>
<S T="2021-05-11 22:57:00" V="851.350"/>
<S T="2021-05-11 22:58:04" V="835.500"/>
<S T="2021-05-11 22:59:08" V="864.910"/>
<S T="2021-05-11 23:00:01" V="847.200"/>
<S T="2021-05-11 23:01:06" V="889.710"/>
<S T="2021-05-11 23:02:10" V="904.190"/>
<S T="2021-05-11 23:03:03" V="912.240"/>
<S T="2021-05-11 23:04:08" V="914.480"/>
<S T="2021-05-11 23:05:01" V="847.350"/>
<S T="2021-05-11 23:06:06" V="857.590"/>
<S T="2021-05-11 23:07:10" V="746.670"/>
<S T="2021-05-11 23:08:04" V="672.460"/>
<S T="2021-05-11 23:09:08" V="652.500"/>
<S T="2021-05-11 23:10:01" V="606.750"/>
<S T="2021-05-11 23:11:06" V="665.510"/>
<S T="2021-05-11 23:12:10" V="701.780"/>
<S T="2021-05-11 23:13:03" V="712.170"/>
<S T="2021-05-11 23:14:07" V="661.140"/>
<S T="2021-05-11 23:15:01" V="704.820"/>
<S T="2021-05-11 23:16:05" V="702.130"/>
<S T="2021-05-11 23:17:09" V="638.590"/>
<S T="2021-05-11 23:18:03" V="616.890"/>
<S T="2021-05-11 23:19:07" V="696.870"/>
<S T="2021-05-11 23:20:01" V="721.010"/>
<S T="2021-05-11 23:21:05" V="657.060"/>
<S T="2021-05-11 23:22:09" V="623.570"/>
</Statistics>
```

**Comment by christianTF** [comment]
Please show source of the /stats request

**Comment by madito** [comment]
![image](https://user-images.githubusercontent.com/5938785/117889147-53d09200-b2b3-11eb-9c36-c46515c14364.png)

**Comment by christianTF** [comment]
And import still not working?

**Comment by madito** [comment]
The same error log:

![image](https://user-images.githubusercontent.com/5938785/117889392-c477ae80-b2b3-11eb-8341-808df858ea83.png)

**Comment by christianTF** [comment]
Possibly we need to trace that directly on your installation.

The getStatlist correctly states the found statistics
```
22:42:18.287 Loxone::Import::getStatlist--> Number of lines 8
22:42:18.287 Loxone::Import::getStatlist--> Number of different uuids 4
```
that matches to your /stats output, but for some reason it does not return the months of the selected element (where also log<->/stats call matches).
The statslistcache only lives for 15 minutes and is downloaded again - therefore, the cache file already should have been current.
