### ISSUE TITLE
Import Error - No stadistics

### ISSUE THREAD

**Issue by madito** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#55]
22:42:22.914 INFO: LoxBerry Version 2.2.0.5 ( is_vmware.cfg is_x64.cfg )
22:42:22.914 INFO: Stats4Lox Version 0.0.1
22:42:22.914 INFO: Loglevel: 7
22:42:22.936 Loxone::Import::statusgetfile--> Creating status file
22:42:22.944 INFO: Loxone::Import::statusgetfile--> Status file: /opt/loxberry/data/plugins/stats4lox/import/import_1_115e8b26-00db-1473-ffffd4fcec132aee.json
22:42:22.945 INFO: --> Logfile: /opt/loxberry/log/plugins/stats4lox/20210511_224222_860_Import_Stats.log
22:42:22.947 Loxone::Import::new--> Called
22:42:22.948 Loxone::Import::getStatsjsonElement--> Called
22:42:22.948 Loxone::Import::getStatsjsonElement--> Opening stats.json (/opt/loxberry/config/plugins/stats4lox/stats.json)
22:42:22.949 Loxone::Import::getStatsjsonElement--> Searching for 115e8b26-00db-1473-ffffd4fcec132aee and 1
22:42:22.950 Loxone::Import::getStatsjsonElement--> Found 1 elements
22:42:22.951 Loxone::Import::getStatsjsonElement--> Found stat name 01 01 Actuador Válvula Tree No detectada
22:42:22.951 INFO: Loxone::Import::getLoxoneLabels--> Querying MS1 to get output labels
mshttp_call2: timeout=5
mshttp_call2: HTTP 200: 200 OK
mshttp_call2:Some lines of the response:
{&quot;LL&quot;: { &quot;control&quot;: &quot;dev/sps/io/115e8b26-00db-1473-ffffd4fcec132aee/all&quot;, &quot;value&quot;: &quot;0&quot;, &quot;Code&quot;: &quot;200&quot;,
&quot;output0&quot;: { &quot;name&quot;: &quot;Q&quot;, &quot;nr&quot;: 1, &quot;value&quot;: 0},
&quot;output1&quot;: { &quot;name&quot;: &quot;&quot;, &quot;nr&quot;: 2, &quot;value&quot;: 0}
}}
[...]
22:42:23.281 Loxone::Import::setMappings--> Called
22:42:23.281 Loxone::Import::setMappings--> Stat element type is TreeSensor
22:42:23.282 INFO: Loxone::Import::setMappings--> Used mapping is: «0»→«Default»
22:42:23.283 Loxone::Import::getStatlist--> Called
22:42:23.283 Loxone::Import::getStatlist--> Checking for cached statlist of 1
22:42:23.284 Loxone::Import::getStatlist--> Reading cache file /dev/shm/s4ltmp/msstatlist_ms1.tmp
22:42:23.284 Loxone::Import::getStatlist--> Parsing response
22:42:23.284 Loxone::Import::getStatlist--> Number of lines 8
22:42:23.284 Loxone::Import::getStatlist--> Number of different uuids 4
22:42:23.285 Loxone::Import::getStatlist--> Finished ok
22:42:23.285 CRITICAL: --> getStatList: Could not get Statistics list from Loxone Miniserver MS1 --> Can't use an undefined value as an ARRAY reference at /opt/loxberry/bin/plugins/stats4lox/libs/Loxone/Import.pm line 182.

22:42:23.286 Loxone::Import::DESTROY-->: Called
22:42:23.287 CRITICAL: main::END--> Import exited with error.

![2](https://user-images.githubusercontent.com/5938785/117882876-123be900-b2ab-11eb-8449-da97aca88e40.JPG)

**Comment by Woersty** [comment]
![image](https://user-images.githubusercontent.com/20454116/117893210-4d91e400-b2ba-11eb-91ee-340ab1bd6cd7.png)

Hab ich auch.

**Comment by christianTF** [comment]
So I see two different errors:
- There is really no stat file -> That should be accepted as ok, nothing to do
- There is only one month file. This could be the common Perl coding mistake, that 0 and null cannot be distinguished.
