### ISSUE TITLE
identische Wertbeschreibung in Loxone -> Grafana Anzeigefehler

### ISSUE THREAD

**Issue by flibbi2** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#59]
Feld "Measurement Label in Statistic" im Standard mit identischer Bezeichnung bei unterschiedlichen Sensoren ergibt ein Statistik Hopping zwischen 2 Werten, siehe Screenshots..

Problem ist eine identische Beschreibung in Loxone für 2 Sensoren.

<img width="1730" alt="2021-05-11_22-16-54" src="https://user-images.githubusercontent.com/78559647/117930318-22c97f00-b2fe-11eb-998d-0ee0b288f8b1.png">
<img width="2376" alt="stats4lox" src="https://user-images.githubusercontent.com/78559647/117930320-23621580-b2fe-11eb-85e1-dc561fc8f754.png">

<img width="1542" alt="grafana" src="https://user-images.githubusercontent.com/78559647/117930307-20672500-b2fe-11eb-966a-5f6771d3efce.png">
<img width="1542" alt="2021-05-11_22-10-29" src="https://user-images.githubusercontent.com/78559647/117930312-2230e880-b2fe-11eb-8020-df5c265b03e0.png">

**Comment by flibbi2** [comment]
Gestern Abend die Loxone Beschreibung angepasst und siehe da, schon klappts:

<img width="1701" alt="2021-05-12_08-45-32" src="https://user-images.githubusercontent.com/78559647/117930589-76d46380-b2fe-11eb-93f9-219476224cb4.png">

**Comment by christianTF** [comment]
Related to #57

**Comment by christianTF** [comment]
Das "Hüpfen" selbst ergibt sich aus folgendem Umstand:
- Der measurementname von zwei unterschiedlichen Loxone Elementen ist gleich
- Der S4L Grabber bezieht die zwei Werte (~600-800, und ~23) anhand der Loxone UUID eindeutig vom Miniserver, schreibt sie aber mit dem gleichen Measurementname in die Datenbank
- Grafana visualisiert diese nun gemeinsam unter einem Measurementname gespeicherten Werte nach deren Timestamps - ein Wert ~600, gefolgt von ~23, wieder ~600 usw.

**Comment by mschlenstedt** [comment]
@christianTF Könntest Du beim Einlesen der LoxConfig auf gleiche Measurementnamen prüfen bzw. ob diese in der stats.json schon gesetzt sind? Dann entsprechend einen anderen Namen als Default einsetzen (z. B. mit Endung "_01" oder so etwas).

**Comment by christianTF** [comment]
Ich werde beim automatischen Setzen, sowie beim Tippen durch User einen Check über alle Stats machen:
- [ ] Automatisches Setzen: Fallback1->Name, Fallback2->Description+RandId
- [ ] Usereingabe: Highlighting rot
- [ ] Usereingabe und bei Fehler Feld verlassen -> Automatisches Setzen wie oben

**Comment by christianTF** [comment]
Die Funktion tritt immer in Kraft:
- beim automatischen Vorbelegen des Measurementnames durch das UI
- beim Ändern durch den Benutzer

Verhalten:
Wird ein Duplikat gefunden, wird ein Fallback in dieser Reihenfolge versucht (**Eingabe** ist die Benutzereingabe):
- Fallback von der **Eingabe** auf `Description`
- Fallback von der **Eingabe** auf `Name`
- Fallback von der **Eingabe** auf `Eingabe_2`
- Fallback von der **Eingabe** auf `Eingabe_3`
- usw. 
bis der Counter bei 20 ist, danach wird eine Exception geworfen (mit hoher Wahrscheinlichkeit ein Fehler im Code)

Es gibt
- kein Highlighting eines Duplikats
- keine spezielle Meldung an den Benutzer (wird einfach still ausgetauscht, ist aber eh sofort sichtbar)
- es passiert _nicht rückwirkend_
