### ISSUE TITLE
Grafana - Datenquelle Standardmäßig auf Stats4Lox ändern

### ISSUE THREAD

**Issue by flibbi2** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#60]
Enhancement:

Datenquelle standardmäßig auf Stats4Lox ändern, aktuell erscheint immer folgendes Bild beim anlegen eines neuen Dashboards:

<img width="2199" alt="2021-05-12_17-19-09" src="https://user-images.githubusercontent.com/78559647/118000578-3993c400-b346-11eb-98ac-a3cf03e16f72.png">

**Comment by mschlenstedt** [comment]
Die Konfiguration von Grafana ist wirklich mies dokumentiert. Aktuell setzen wir in der Dateasource-Konfiguration bereits:

`is_default: true`

Das scheint aber nicht zu reichen...

**Comment by mschlenstedt** [comment]
Ah, typo, es muss sein:

`isDefault: true`

Dann ist die Datenquelle auch als Default markiert. 

![image](https://user-images.githubusercontent.com/16830799/118238752-3fe68500-b499-11eb-8e3d-ccc14a0bacbf.png)
