### ISSUE TITLE
Grafana: unauthorized

### ISSUE THREAD

**Issue by Woersty** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#61]
https://user-images.githubusercontent.com/20454116/118013939-f55af080-b352-11eb-8eb5-6d6401860e4d.mp4

**Comment by Woersty** [comment]
purge und neu installiert - noch genauso => Unauthorized

**Comment by Woersty** [comment]
http://192.168.178.50:3000/api/user/helpflags/1  => Response {"message":"Unauthorized"}

![image](https://user-images.githubusercontent.com/20454116/118028939-f1839a00-b363-11eb-9b7c-80c966728f13.png)

**Comment by flibbi2** [comment]
Ich habe das ebenfalls.

**Comment by mschlenstedt** [comment]
@christianTF hats kaputt gemacht ;-)

Nein, im Ernst - ich schaue es mir an.

**Comment by mschlenstedt** [comment]
Kann ich nachstellen. Wir haben die Benutzerauthentifizierung in Grafana per Default deaktiviert. Man kann so neue Dahsboards anlegen etc. pp., aber anscheinend hat man so auf General / Home keinen Zugriff.

Selbst wenn man sich als Admin unten links einloggt (loxberry / loxberry), hat man keinen Zugriff. Das müssen wir uns noch einmal anschauen. Vielleicht irgendetwas mit Filepermissions?

**Comment by mschlenstedt** [comment]
I tried to fix this, but without success...

I even cannot switch back to authorization of grafana. After activating, the login apperas, I can log in but will never be redirected than to grafana home. I always be directed to the login screen again and again.

We hae to fix the whole grafana config in total!

**Comment by mschlenstedt** [comment]
Vermutlich ist es dieses Problem: https://community.grafana.com/t/chrome-and-edge-do-not-accept-correct-login-data-firefox-works/44567

Das Problem besteht mit Chrome und darauf basierenden Browsern (z. B. Edge). Firefox und Safari funktionieren (noch).

Wir hatten aus den Anfangszeiten cookie_samesite = none gesetzt, weil sonst die Dashboards auf der Pluginstartseite nicht funktionierten (diese waren über "localhost" eingebunden). Chrome blockiert solche Cookies, wenn sie nicht über eine HTTPS-Verbindung kommen. Mittlerweile nutzen wir auf der Pluginstartseite dynamisch generierte Links mit der IP-Adresse des LoxBerrys, daher ist diese "lockere" Option nicht mehr nötig.

Daher können nun cookie_samesite = strict setzen, was für Chrome und Co. in Ordnung ist.

Eventuell müssen die Cookies einmalig in Chrome gelöscht werden.
