### ISSUE TITLE
ParseXML - SN (Mac) als Identifier verwenden

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#67]
Für lokale und Cloud DNS Miniserver

- Vorab alle MACs der Miniserver abrufen (/dev/cfg/mac)
- Beim Parsing auf die SN matchen (Abruf der Mac <-> Loxplan)
- Fallback auf Hostname/IP

Sollte implizit auch das Problem bei Cloud DNS lösen, wenn ein LoxBerry Miniserver mehrerer Haushalte via Cloud DNS einsammelt, die ggf. die gleiche lokale IP verwenden.

**Comment by Woersty** [comment]
Aussperren von CloudDNS bei zuvielen Abfragen von der gleichen IP aus beachten. 
Deshalb würde ich vorschlagen, dass man die Miniserver definieren kann, die abgefragt werden sollen.
Und das müsste auf max. begrenzt werden damit die Sperre nicht zuschlägt.
Warum kannst du nicht einfach alle Miniserver aus der globalen MS config holen und erst wenn man im WebUI des Plugins aus dem Dropdown einen auswählt, holt er die Werte von dem. Das Plugin wird dann halt auf max. X Miniserver begrenzt die gleichzeitig erfasst werden können.

**Comment by christianTF** [comment]
1. Deaktivieren von MS ist Teil von #16 

2. Weil das nicht _einfach_ ist, und das die Extrawurst für dich wäre. Ich und die meisten wollen in allen Elementen suchen, nicht nur in einem MS.
