### ISSUE TITLE
Imports without Loxone Stats: Log ok, but scheduler says dead

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#76]
Imports without Loxone Statistics correctly log „Nothing to do“ (without errors), but seem to be classified as „Dead“ in some circumstances (not always) by the scheduler.

**Comment by mschlenstedt** [comment]
Maybe already fixed?

**Comment by christianTF** [comment]
Was fixed with https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/commit/63bd7310ac18452e6d143eaedc385e4507fc9180
