### ISSUE TITLE
ERROR: APT install: (Some) Packages could not be installed

### ISSUE THREAD

**Issue by alealdata** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#80]
[g7PRuHg0NO.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG/files/6506738/g7PRuHg0NO.log)

Bei der Installation des Plugins können nicht alle Pakete installiert werden und die Grafana Seite kann nicht geöffnet werden da auch kein Neustart möglich ist.
Alle anderen Logs sind unauffällig bis auf die bekannte Tree2Air Geschichte.

![Error](https://user-images.githubusercontent.com/37976222/118774041-b44c6a00-b885-11eb-96cd-11721d1a8968.JPG)

**Comment by christianTF** [comment]
```
Unpacking grafana (7.5.6) over (2.6.0+dfsg-3+b1) ...
dpkg: error processing archive /var/cache/apt/archives/grafana_7.5.6_armhf.deb (--unpack):
 trying to overwrite '/usr/share/grafana/conf/defaults.ini', which is also in package grafana-data 2.6.0+dfsg-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../telegraf_1.18.2-1_armhf.deb ...
Unpacking telegraf (1.18.2-1) over (1.18.2-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/grafana_7.5.6_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mschlenstedt** [comment]
Bei mir gerade problemlos gelaufen. Sollten wir beobachten - vielleicht irgendein Problem mit dem Paket.

**Comment by christianTF** [comment]
Schaut aus, als würde Grafana bereits installiert gewesen sein.

**Comment by mschlenstedt** [comment]
Tritt nicht mehr auf - zumindest bei meiner frischen Installation nicht. Ich mach es vorerst zu,
