### ISSUE TITLE
Upgrade: Backup contains all previous backups

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#84]
The backup on upgrade always contains the zips of every previous update.

Therefore, the backup size and backup time doubles each update.

![image](https://user-images.githubusercontent.com/14220265/120012439-ccd42700-bfdf-11eb-910e-167f566d5678.png)

**Comment by mschlenstedt** [comment]
Absicht.

**Comment by mschlenstedt** [comment]
Ah nee, dass ist keine Absicht. Die nehme ich raus.
