### ISSUE TITLE
Adjust ~/bin/provisioning Skripts?

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Stats4Lox-NG#97]
Neeeded because of changing Grafana back to user "grafana".

To be checked.

**Comment by christianTF** [comment]
Bisher scheint die Änderung der User keine Auswirkung auf das Provisioning gehabt zu haben (keine Meldungen, dass das Provisioning nicht funktioniert hätte).
Deswegen schließe ich das mal.
